version: '2'
services:
  server:
    network_mode: "bridge"
    image: launch-server
    build:
      context: ./server
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    command: bundle exec foreman start --env config/foreman/local.dev.env
    env_file: server/config/foreman/local.dev.env
    volumes:
      - ./server:/app
    ports:
      - "4003:4003"
    links:
      - db

  db:
    network_mode: "bridge"
    image: postgres:9.5
