version: '2'
services:
  client:
    image: launch-client
    build:
      context: ./client
      args:
        - USER_ID=${USER_ID}
    volumes:
      - ./client:/home/launch/launch
      - ${HOME}/.cache/yarn:/home/launch/.cache/yarn
      - ../flight-common:/home/flight-common
    links:
      - server
    ports:
      - "4002:4002"

  server:
    image: launch-server
    build:
      context: ./server
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    command: bundle exec foreman start --env config/foreman/local.dev.env
    # command: bash -c "export BUNDLE_APP_CONFIG=/app/.bundle ; bundle install --local && bundle exec foreman start --env config/foreman/local.dev.env"
    env_file: server/config/foreman/local.dev.env
    volumes:
      - ./server:/app
    ports:
      - "4003:4003"
