# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a98dd12a5f6dea1b4c3dbdd07cf08e5a53014efdc21e5d06831a7d7a1455809247ca69364e80834fef229b3b0bf08c442372938e1a10e2f5d3ff7b3f91c646
  json_web_token_secret: cabfa4559f1d674ee86e423a4a849f450393630dfc2c48b2a949efb8df510357f602b5cab6584668452d7e0eba961d5c88be6194d978eb1d7d5d55ce5ecbc204

test:
  secret_key_base: 9845cdc5b3e1ac0e138c4db022cd19768db3e2b654de3500b0fab4a6e17ffafc1fe0da20c0bec80bb5a47876e33a6af8a269a08b0daf1a4300d2eafe42f746db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  json_web_token_secret: <%= ENV['JSON_WEB_TOKEN_SECRET'] %>
